# Flexiforce settings
port               : /dev/ttyACM0
baud               : 2000000

useCurrentCartPose : false
useNullspacePose   : false
useFTinput         : true
forceTorqueOn      : true
useFlexiForce      : false

# Specifically for MRAC
useSimHuman        : true

# Only one can be true
useARMAmodel       : false
useCTARMAmodel     : false
useFIRmodel        : false
useMRACmodel       : true
useIRLmodel        : false
useMSDmodel        : false
useDirectmodel     : false

outerLoop_time     : 0.001

# Is the reference trajectory x_r or q_r set externally or estimated
# If externalRefTraj is false the human intent x_i is used
# i.e. an admittance model is used to generate x_i from f_h the force from the FT sensor
externalRefTraj    : true

# Human intent estimation
intentEst_time     : 0.05
intentEst_delT     : 0.1  # Propagation time
intentEst_M        : 1.0  # M_i the mass of the intent admittance model

# The params of the RLS estimator
rls_lambda         : 0.98
rls_sigma          : 0.001

# IRL
numIrlSamples      : 200
numIrlLsIter       : 20
numCartDof         : 1
irlOneshot         : true

# Params for the MRAC outer-loop controller
mrac_gamma_1       : 0.1
mrac_gamma_2       : 2.0
mrac_gamma_3       : 2.5
mrac_gamma_4       : 4
mrac_gamma_5       : 4

mrac_P_m           : 1
mrac_P_h           : 1

fixedFilterWeights : false

# ARMA parameters
filtW0                : -1.8775  #-1.8136 #-2.3646
filtW1                :  1.2729  # 1.3171 # 1.9237
filtW2                : -0.0578  #-0.4726 #-0.3255
filtW3                : -0.3269  #-0.0082 #-0.1816
filtW4                :  0.0018  # 0.0032 # 0.0049
filtW5                :  0.0001  #-0.0010 #-0.0018
filtW6                : -0.0013  #-0.0007 #-0.0018
filtW7                :  0.0002  #-0.0009 # 0.0014

# ARMA parameters for flexiforce          
flex_1_filtW0         :  0.0
flex_1_filtW1         :  0.0
flex_1_filtW2         :  0.0
flex_1_filtW3         :  0.0
flex_1_filtW4         :  0.0
flex_1_filtW5         :  0.0
flex_1_filtW6         :  0.0
flex_1_filtW7         :  0.0
                        
flex_2_filtW0         : -0.6283
flex_2_filtW1         : -0.3757
flex_2_filtW2         :  0.1192
flex_2_filtW3         : -0.1512
flex_2_filtW4         :  0.0063
flex_2_filtW5         : -0.0017
flex_2_filtW6         : -0.0030
flex_2_filtW7         :  0.0026
                      
flex_3_filtW0         :  0.0
flex_3_filtW1         :  0.0
flex_3_filtW2         :  0.0
flex_3_filtW3         :  0.0
flex_3_filtW4         :  0.0
flex_3_filtW5         :  0.0
flex_3_filtW6         :  0.0
flex_3_filtW7         :  0.0
                        
flex_4_filtW0         : -0.7185
flex_4_filtW1         :  0.1265
flex_4_filtW2         : -0.1395
flex_4_filtW3         : -0.2230
flex_4_filtW4         : -0.0009
flex_4_filtW5         :  0.0003
flex_4_filtW6         : -0.0001
flex_4_filtW7         :  0.0013

# This makes zero any force less than below
forceCutOffX          : 0.1
forceCutOffY          : 0.1
forceCutOffZ          : 0.1

# Params for the MSD outer-loop controller
m_M                   : 1.0
m_S                   : 0.0
m_D                   : 5.0

# Params for M(s) of the RLS models
task_mA               : 6.0
task_mB               : 6.0

# Params for MRAC Sim Human
simHuman_a            : 0.1
simHuman_b            : 2.6

# cartIniX            :  0.7
# cartIniY            :  0.0
# cartIniZ            :  0.1
# cartIniRoll         :  0.0
# cartIniPitch        :  0.0
# cartIniYaw          :  0.0

cartIniX              :  0.7
cartIniY              :  0.0
cartIniZ              : -0.1
cartIniRoll           :  0.0
cartIniPitch          :  0.0
cartIniYaw            :  0.0

# cartDesX            :  0.7
# cartDesY            : -0.3
# cartDesZ            :  0.1
# cartDesRoll         :  0.0
# cartDesPitch        :  0.0
# cartDesYaw          :  0.0

cartDesX              :  0.7
cartDesY              :  0.3
cartDesZ              : -0.1
cartDesRoll           :  0.0
cartDesPitch          :  0.0
cartDesYaw            :  0.0

cartDes2X             :  0.9
cartDes2Y             :  0.3
cartDes2Z             : -0.1
cartDes2Roll          :  0.0
cartDes2Pitch         :  0.0
cartDes2Yaw           :  0.0

cartDes3X             :  0.9
cartDes3Y             :  0.0
cartDes3Z             : -0.1
cartDes3Roll          :  0.0
cartDes3Pitch         :  0.0
cartDes3Yaw           :  0.0

# lCartIniX           :  0.8
# lCartIniY           :  0.05
# lCartIniZ           :  0.0
# lCartIniRoll        :  1.57079633
# lCartIniPitch       :  0.0
# lCartIniYaw         : -1.57079633

lCartIniX             :  0.6
lCartIniY             : -0.3
lCartIniZ             :  0.0
lCartIniRoll          :  1.57079633
lCartIniPitch         :  0.0
lCartIniYaw           :  1.57079633

circleRate            : 1
circleLlim            : 0.5
circleUlim            : 1.5

nnNum_Inputs          : 35 
nnNum_Outputs         : 7
nnNum_Hidden          : 10
nnNum_Error           : 7  
nnNum_Joints          : 7  

# Filtered error
# r = (qd_m - qd) + lambda*(q_m - q);
# Kv*r

nn_Kv                 : 5
nn_lambda             : 20
nn_kappa              : 0.3
nn_Kz                 : 0.001 
nn_Zb                 : 100 
nn_feedForwardForce   : 1   
nn_nnF                : 100 
nn_nnG                : 200
nn_ON                 : 1

# nn_Kv               : 5
# nn_lambda           : 20
# nn_kappa            : 0.07
# nn_Kz               : 0.001 
# nn_Zb               : 1000 
# nn_feedForwardForce : 0   
# nn_nnF              : 100 
# nn_nnG              : 100
# nn_ON               : 1

cartPos_Kp_x          : 60.0
cartPos_Kp_y          : 60.0
cartPos_Kp_z          : 60.0
cartPos_Kd_x          : 10
cartPos_Kd_y          : 10
cartPos_Kd_z          : 10

cartRot_Kp_x          : 9.0
cartRot_Kp_y          : 9.0
cartRot_Kp_z          : 9.0
cartRot_Kd_x          : 3
cartRot_Kd_y          : 3
cartRot_Kd_z          : 3

# Nominal angles for the arm joints
                # Left arm          # Right arm
nom_joint_0  :  0.0    # 0.067      # -0.48577  
nom_joint_1  :  0.0    # 0.036      # -0.0190721
nom_joint_2  :  1.5828 # 0.012      # -1.51115  
nom_joint_3  : -0.5    #-0.097      # -1.70928  
nom_joint_4  :  0.0    #-0.983      #  1.54561  
nom_joint_5  :  0.0    #-0.0947     #  0.046854 
nom_joint_6  :  0.0    # 0.1114     # -0.0436174

pr2_cartesianController:
  type: PR2CartesianControllerClass
  root_name: torso_lift_link
  tip_name: r_gripper_tool_frame

pr2_cartneuroController:
  type: ice_robot_controllers/PR2CartneuroControllerClass
  root_name: torso_lift_link
  tip_name: l_gripper_tool_frame

pr2_cartresnnController:
  type: PR2CartresnnControllerClass
  root_name: torso_lift_link
  tip_name: r_gripper_tool_frame

pr2_explforceController:
  type: PR2ExplforceControllerClass
  root_name: torso_lift_link
  tip_name: r_gripper_tool_frame

pr2_impedanceController:
  type: PR2ImpedanceControllerClass
  root_name: torso_lift_link
  tip_name: r_gripper_tool_frame 

pr2_neuroadptController:
  type: PR2NeuroadptControllerClass
  root_name: torso_lift_link
  tip_name: l_gripper_tool_frame

pr2_pidController:
  type: PR2PidControllerClass
  root_name: torso_lift_link
  tip_name: l_gripper_tool_frame

saturation:
  l_shoulder_pan_joint: 11.88
  l_shoulder_lift_joint: 11.64
  l_upper_arm_roll_joint: 6.143
  l_elbow_flex_joint: 6.804
  l_forearm_roll_joint: 8.376
  l_wrist_flex_joint: 5.568
  l_wrist_roll_joint: 5.568
  r_shoulder_pan_joint: 11.88
  r_shoulder_lift_joint: 11.64
  r_upper_arm_roll_joint: 6.143
  r_elbow_flex_joint: 6.804
  r_forearm_roll_joint: 8.376
  r_wrist_flex_joint: 5.568
  r_wrist_roll_joint: 5.568

